name = (input('Qual é seu nome? '))
print (f'Olá {name}! Iremos te ajudar com porcentagem em Python!\n Vamos nessa!')
teach = (input('Digamos que você queira saber (5%) ou (10%), ok? '))
print ('  ')
print (f'Ótimo {name}! Seja qual número for você sempre irá usar está forma.\n')
print ('Em seu terminal você irá escrever assim (considerando que você quer saber (5%) de 10) (10*5/100) \n')
print ('Esse (10*5/100), você irá ler desta maneira. (Cinco ''porCENto'' de dez) \n')
print ('O número 10 é 100%! Então você está mandando o Python fazer a seguinte forma \n')
print ('Quero saber CINCO porCENto de 10, ele te entregará a seguinte forma (0.5) \n')
print ('Exemplo (10%) de 1500, como você irá fazer! (1500*10/100)! Ele te entregará isso: \n')
tounderstand = input ('(150.O). Ficou um pouco mais facíl de entender? Espero que sim! (Aperte (Enter) para prosseguir!) :)')
print (    )
number1 = float(input('Digite um número que você queira saber de %5, ok? '))
number2 = float (input('Digte um outro valor que você queira saber de %10, ok? '))
valor1 = (number1 * 0.05)
valor2 = (number2 * 0.10)
print (f'Cinco porcento de {number1} é {valor1:.1f}!\nDez porcento de {number2} é {valor2:.1f}\n')
print (f'Agora é com você {name}! Faça um programa que leia 25% de (número de sua preferência) e 55% (também um número de sua preferência!)\n ')
print ('Sempre conferir se a porcentagem está certa! Confira no Google!!\n')
print ('Usando essa forma para porcentagem você acertará sempre, se armar certo! Pressione Enter para prosseguir.')
input ('Digamos que você quer saber (4%) de 253, você armará desta forma! (253*4/100). Entendido?')
print (f'Espero que tenha entendido {name}! Em caso de dúvidas refazer esse processo diversas vezes!!')